package testnet.andy.testnetworkstatus.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import testnet.andy.testnetworkstatus.db.greendao.entity.TrafficModel;

import testnet.andy.testnetworkstatus.db.greendao.TrafficModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trafficModelDaoConfig;

    private final TrafficModelDao trafficModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trafficModelDaoConfig = daoConfigMap.get(TrafficModelDao.class).clone();
        trafficModelDaoConfig.initIdentityScope(type);

        trafficModelDao = new TrafficModelDao(trafficModelDaoConfig, this);

        registerDao(TrafficModel.class, trafficModelDao);
    }
    
    public void clear() {
        trafficModelDaoConfig.getIdentityScope().clear();
    }

    public TrafficModelDao getTrafficModelDao() {
        return trafficModelDao;
    }

}
